<a href="https://colab.research.google.com/github/esmanurarslan/4th_grade_hw/blob/main/collabrotive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
movies= pd.read_csv("/content/drive/MyDrive/Data_Mining/movielens/movies.csv")

In [ ]:
# reading the ratings dataset
ratings = pd.read_csv('/content/drive/MyDrive/Data_Mining/movielens/ratings.csv')

In [ ]:
# creating a pivot table
pd.pivot_table(ratings, index='userId', columns='movieId', values='rating')

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# filling the missing values in the pivot table with 0 and converting to DataFrame
df = pd.DataFrame(pd.pivot_table(ratings, index='userId', columns='movieId', values='rating', fill_value=0))
df

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# importing the packages
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

**user-based approach**

In [ ]:
# computing pairwise distances using cosine similarity between the users
distance_matrix = pairwise_distances(df, metric='cosine')

In [ ]:
# finding the top 5 most similar users
(distance_matrix[9]).argsort()[1:6]+1

array([159, 143, 563, 177, 189])

In [ ]:
# pairwise_distances ile kullanıcılar arasındaki cosine distance hesaplıyoruz
distance_matrix = pairwise_distances(df, metric='cosine')

# distance_matrix numpy array dönecektir, bu yüzden pandas DataFrame'e çevirelim
distance_df = pd.DataFrame(distance_matrix, index=df.index, columns=df.index)

# Kullanıcı 10 ve kullanıcı 159 arasındaki benzerliği kontrol edelim (benzerlik = 1 - cosine distance)
similarity_score = 1 - distance_df.loc[10, 159]
print(f"Cosine similarity between User 10 and User 159: {similarity_score:.2f}")

Cosine similarity between User 10 and User 159: 0.29

In [ ]:
# finding the intersection of the sets of the movies that both users 10 and 159 have watched
set(ratings.loc[ratings.userId==10, 'movieId']).intersection(set(ratings.loc[ratings.userId==159, 'movieId']))

{296,
 356,
 597,
 1088,
 1307,
 1784,
 2671,
 2858,
 2959,
 4246,
 4306,
 4447,
 5377,
 5957,
 6377,
 6942,
 8533,
 8969,
 31685,
 40819,
 47099,
 49286,
 56367,
 64969,
 68954,
 72998,
 81845,
 84374,
 88810,
 95167,
 104374,
 106696,
 106782,
 140110}

In [ ]:
# Verilen movieId'leri filtrele
movie_ids_to_check = {296, 356, 597, 1088, 1307, 1784, 2671, 2858, 2959, 4246, 4306,
                      4447, 5377, 5957, 6377, 6942, 8533, 8969, 31685, 40819, 47099,
                      49286, 56367, 64969, 68954, 72998, 81845, 84374, 88810, 95167,
                      104374, 106696, 106782, 140110}

# Sadece ilgili movieId'leri ve kullanıcıları seç
filtered_ratings = ratings[(ratings['movieId'].isin(movie_ids_to_check)) &
                           (ratings['userId'].isin([10, 159]))]

# Filmleri ve puanları birleştir
merged_data = pd.merge(filtered_ratings, movies, on="movieId")

# Çıktıyı formatlayarak grupla
for movie_id, group in merged_data.groupby("movieId"):
    title = group["title"].iloc[0]
    print(f"Movie ID {movie_id}: {title}")
    for _, row in group.iterrows():
        print(f"Rating by User {row['userId']}: {row['rating']}")
    print()  # Boşluk bırak

Movie ID 296: Pulp Fiction (1994)
Rating by User 10: 1.0
Rating by User 159: 0.5

Movie ID 356: Forrest Gump (1994)
Rating by User 10: 3.5
Rating by User 159: 4.0

Movie ID 597: Pretty Woman (1990)
Rating by User 10: 3.5
Rating by User 159: 4.0

Movie ID 1088: Dirty Dancing (1987)
Rating by User 10: 3.0
Rating by User 159: 4.0

Movie ID 1307: When Harry Met Sally... (1989)
Rating by User 10: 3.0
Rating by User 159: 4.5

Movie ID 1784: As Good as It Gets (1997)
Rating by User 10: 3.5
Rating by User 159: 2.5

Movie ID 2671: Notting Hill (1999)
Rating by User 10: 3.5
Rating by User 159: 3.0

Movie ID 2858: American Beauty (1999)
Rating by User 10: 1.0
Rating by User 159: 4.0

Movie ID 2959: Fight Club (1999)
Rating by User 10: 0.5
Rating by User 159: 3.0

Movie ID 4246: Bridget Jones's Diary (2001)
Rating by User 10: 3.5
Rating by User 159: 5.0

Movie ID 4306: Shrek (2001)
Rating by User 10: 4.5
Rating by User 159: 4.0

Movie ID 4447: Legally Blonde (2001)
Rating by User 10: 4.5
Rating by User 159: 2.5

Movie ID 5377: About a Boy (2002)
Rating by User 10: 3.5
Rating by User 159: 2.0

Movie ID 5957: Two Weeks Notice (2002)
Rating by User 10: 3.0
Rating by User 159: 3.0

Movie ID 6377: Finding Nemo (2003)
Rating by User 10: 3.5
Rating by User 159: 4.5

Movie ID 6942: Love Actually (2003)
Rating by User 10: 4.0
Rating by User 159: 4.5

Movie ID 8533: Notebook, The (2004)
Rating by User 10: 5.0
Rating by User 159: 4.0

Movie ID 8969: Bridget Jones: The Edge of Reason (2004)
Rating by User 10: 3.5
Rating by User 159: 2.0

Movie ID 31685: Hitch (2005)
Rating by User 10: 4.5
Rating by User 159: 3.0

Movie ID 40819: Walk the Line (2005)
Rating by User 10: 4.0
Rating by User 159: 3.5

Movie ID 47099: Pursuit of Happyness, The (2006)
Rating by User 10: 3.0
Rating by User 159: 5.0

Movie ID 49286: Holiday, The (2006)
Rating by User 10: 5.0
Rating by User 159: 2.0

Movie ID 56367: Juno (2007)
Rating by User 10: 3.5
Rating by User 159: 5.0

Movie ID 64969: Yes Man (2008)
Rating by User 10: 0.5
Rating by User 159: 4.0

Movie ID 68954: Up (2009)
Rating by User 10: 4.0
Rating by User 159: 3.0

Movie ID 72998: Avatar (2009)
Rating by User 10: 2.5
Rating by User 159: 4.0

Movie ID 81845: King's Speech, The (2010)
Rating by User 10: 5.0
Rating by User 159: 3.5

Movie ID 84374: No Strings Attached (2011)
Rating by User 10: 3.5
Rating by User 159: 3.0

Movie ID 88810: Help, The (2011)
Rating by User 10: 3.0
Rating by User 159: 3.5

Movie ID 95167: Brave (2012)
Rating by User 10: 4.0
Rating by User 159: 3.5

Movie ID 104374: About Time (2013)
Rating by User 10: 4.0
Rating by User 159: 5.0

Movie ID 106696: Frozen (2013)
Rating by User 10: 4.5
Rating by User 159: 3.0

Movie ID 106782: Wolf of Wall Street, The (2013)
Rating by User 10: 1.0
Rating by User 159: 2.0

Movie ID 140110: The Intern (2015)
Rating by User 10: 5.0
Rating by User 159: 4.5

In [ ]:

# Kullanıcı 159'un rating değerinin 3.5 üzeri olan filmleri seçiyoruz
user_159_movies = ratings[ratings['userId'] == 159]
user_159_high_rating = user_159_movies[user_159_movies['rating'] > 3.5]

# Kullanıcı 10'un izlediği ve kullanıcı 159'un izlediği ortak filmleri bulalım
common_movies = pd.merge(ratings[ratings['userId'] == 10], user_159_high_rating, on="movieId")

# Kullanıcı 159'un 3.5 üzeri puan verdiği ve kullanıcı 10'un izlemediği filmleri öneri olarak alalım
unwatched_movies_by_user_10 = user_159_high_rating[~user_159_high_rating['movieId'].isin(common_movies['movieId'])]

# Önerilen filmleri movie dataframe'inde başlık bilgisiyle birleştirelim
recommended_movies = unwatched_movies_by_user_10[['movieId', 'rating']].merge(movies[['movieId', 'title']], on='movieId')

# Önerilen filmleri yazdıralım
print("Recommended Movies for User 10 based on User 159's ratings (rating > 3.5):")
print(recommended_movies.sort_values(by='rating', ascending=False))

Recommended Movies for User 10 based on User 159's ratings (rating > 3.5):
    movieId  rating                                        title
24   166643     5.0                        Hidden Figures (2016)
16    65230     5.0                           Marley & Me (2008)
20    78499     5.0                           Toy Story 3 (2010)
18    72641     5.0                      Blind Side, The  (2009)
6      1704     5.0                     Good Will Hunting (1997)
17    69757     5.0                  (500) Days of Summer (2009)
23   157296     4.5                          Finding Dory (2016)
22    97304     4.5                                  Argo (2012)
0         1     4.5                             Toy Story (1995)
7      3114     4.5                           Toy Story 2 (1999)
5      1265     4.5                         Groundhog Day (1993)
2       318     4.5             Shawshank Redemption, The (1994)
9      5299     4.0              My Big Fat Greek Wedding (2002)
10     6373     4.0                        Bruce Almighty (2003)
11     7143     4.0                     Last Samurai, The (2003)
1       150     4.0                             Apollo 13 (1995)
13    30707     4.0                   Million Dollar Baby (2004)
14    45720     4.0                Devil Wears Prada, The (2006)
15    64957     4.0  Curious Case of Benjamin Button, The (2008)
8      4886     4.0                        Monsters, Inc. (2001)
19    74946     4.0                She's Out of My League (2010)
4      1197     4.0                   Princess Bride, The (1987)
21    89774     4.0                               Warrior (2011)
3       587     4.0                                 Ghost (1990)
12     8360     4.0                               Shrek 2 (2004)